// Kashmiri UI strings (Perso-Arabic script, RTL).
export const ks = {
  appName: "Kosher AI",
  tagline: "کٲشُر ؤاژ ایسِسٹینٹ",
  typeMessage: "پیغام لِکھِو…",
  micHint: "مائیک دبٲیو تہٕ کٲشُر منز وُنِو",
  recording: "ریکارڈنگ جٲری چھُ…",
  tapAgainToStop: "روکُن خأطرٕ دوبارہ دبٲیو",
  transcribing: "سُنأن چھُ…",
  thinking: "سۆچان چھُ…",
  startChat: "گپ شپ شۆروٗع کٔریو",
  emptyHint: "مائیک دبٲیو تہٕ کٲشُر منز وُنِو — یا لِکھِو",
  chooseVoice: "آواز ژٲریو",
  voiceReply: "آواز سٕتہ جواب",
  voiceReplyOn: "آواز جواب آن چھُ",
  voiceReplyOff: "آواز جواب بند چھُ",
  autospeak: "خُودکار آواز",
  easterHint: "…تھوڑی گٹھ تہٕ",
  passwordTitle: "ڈیویلپر اختیارات",
  passwordSubtitle: "پاس ورڈ دِیو کھولُن خأطرٕ",
  passwordPlaceholder: "••••••",
  unlock: "کھولِو",
  wrongPassword: "پاس ورڈ غلط چھُ — دوبارہ کوشش کٔریو",
  cancel: "ٹالِو",
  save: "محفوظ کٔریو",
  saving: "محفوظ گژھأن چھُ…",
  saved: "محفوظ گیو",
  remove: "مِٹٲیو",
  addVoice: "نئیٚ آواز اِضاف کٔریو",
  clearChat: "گپ شپ صاف کٔریو",
  cleared: "گپ شپ صاف گیہ",
  errorGeneric: "غلطی پیش آئی — مُکرَر کوشش کٔریو",
  noNetwork: "رابطہ نہِ گوو — انٹرنیٹ کٔریو چیک",
  keysMissing: "API کلید نہِ چھُ — ڈیویلپر اختیارات منز دِیو",
  micPermissionTitle: "مائیکروفون اجازت",
  micPermissionBody:
    "تۆہؠ کٔرؠ نال یِہ تہٕ تُہُنٛد ؤاژ سُنأن چھُ — کٲشُر منز وُنُن خأطرٕ مائیکروفون اجازت دِیو",
  micAllow: "اجازت دِیو",
  micDeniedToast: "اجازت نہِ گئی — مائیک کٲم نہِ کری",
  openSettings: "سیٹِنگز کُن گژِو",
  micBlockedBody: "اجازت بند چھُ — سیٹِنگز منز کٔریو کھولُن",
  logoTitle: "اٮ۪پ لوگو",
  logoUpload: "لوگو کٔریو تبدیل",
  logoReset: "ڈیفاڑٹ کُن وٲپس",
  logoUpdated: "لوگو تبدیل گیو",
  logoResetDone: "لوگو واپس گیو",
  testVoice: "آواز کٔریو ٹیسٹ",
  systemPrompt: "سِسٹم پرامپٹ",
  apiKeys: "API کلید",
  sttTitle: "ؤاژ تو۪ن نہ — STT",
  ttsTitle: "آواز اُتارن — TTS",
  llmTitle: "ذہانت — LLM",
  voicesTitle: "آواز ماڈل",
  sttProvider: "STT فراہن کار",
  ttsProvider: "TTS فراہن کار",
  llmModel: "LLM ماڈل",
  sarvamKey: "Sarvam API کلید",
  azureKey: "Azure Speech کلید",
  azureRegion: "Azure علاقہ (region)",
  elevenKey: "ElevenLabs API کلید",
  openaiKey: "OpenAI کلید (اختیاری)",
  voiceLabel: "ناو",
  voiceId: "Voice ID",
  language: "بولی",
  modelName: "ماڈل",
  gender: "جِنس",
  provider: "فراہن کار",
  male: "مَرٕد",
  female: "زَنان",
  notConfigured: "کلید نہِ",
  configured: "کلید چھُ",
  loading: "لۆڈ گژھأن چھُ…",
  retry: "دوبارہ کوشش",
  errorBanner: "رابطہ کہِ غلطی — دوبارہ کوشش کٔریو",
  playVoice: "آواز سُنِو",
  stopVoice: "آواز رَاوِ",
  newChatVoice: "نئیٚ آواز",

  // auth + history
  signIn: "گوگل سٕتؠ سائن اِن",
  signOut: "سائن آوٹ",
  guest: "مہمان",
  guestMode: "مہمان طور اِستٕعمال کٔریو",
  historyTitle: "گٲپھ ہِسٹری",
  newChat: "نۆو گٲپھ",
  noHistory: "وُنہِ کہین گٲپھ چھُ نہٕ",
  signInForHistory: "ہِسٹری بچاوُن خأطرٕ سائن اِن کٔریو",
  deleteChat: "گٲپھ مِٹٲیو",
  menu: "مینو",
  account: "اکاؤنٹ",

  // voice conversation box
  voiceMode: "آواز موڈ",
  tapToSpeak: "وُنُن خأطرٕ دبٲیو",
  listening: "بوزان چھُس…",
  speaking: "وُنان چھُس…",
  processing: "سۆچان چھُس…",
  endVoice: "بند کٔریو",
  voiceHint: "دبٲیو تہٕ کٲشُر منز وُنِو",

  // attachments
  attach: "فایل جوڑیو",
  attachPhoto: "فوٹو",
  attachPdf: "PDF / فایل",
  attaching: "اپلوڈ گژھأن چھُ…",
  removeAttachment: "ہٹٲیو",

  // input script
  inputScript: "لِکھنُک سِکرِپٹ",
  scriptPerso: "کٲشُر / اردو",
  scriptEnglish: "English",
  scriptUrdu: "اردو",

  // dev customization
  customizeTitle: "اٮ۪پ ڈِزائن",
  appNameLabel: "اٮ۪پ ناو",
  taglineLabel: "ٹیگ لائن",
  logoPosition: "لوگو جاۍ",
  posLeft: "کھوفُر",
  posCenter: "بیچ",
  posRight: "دٲچھِن",
  featuresTitle: "فیچرٕ",
  featVoiceMode: "آواز موڈ",
  featAttachments: "فایل جوڑُن",
  featAutoSpeak: "خُودکار آواز",
  featInputSwitcher: "سِکرِپٹ سویچ",
  featShowTagline: "ٹیگ لائن ہاوِو",
  visionModel: "وِژن ماڈل (فایل)",
  characterPhoto: "کریکٹر فوٹو",
  changePhoto: "فوٹو بدلٲیو",
};

export type KS = typeof ks;